FROM php:8.2-cli

RUN apt-get update && apt-get install -y \
        default-mysql-client \
        libonig-dev \
        libzip-dev \
        unzip \
        && docker-php-ext-install pdo pdo_mysql

WORKDIR /var/www/html

CMD ["php", "-S", "0.0.0.0:8000", "index.php"]